# Site settings
title: Lawrence Nonprofit DH Project
email: lawrencenonprofit@gmail.com
url: https://pvldmtra.github.io
description: "This is the website for the nonprofits of Lawrence project for the Digital Humanities class at the University of Kansas.  Centennial Clogston, Haley Nus, and Mike Van Esler researched and constructed this project."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: DH690

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
